// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPOqtwt9qaajf_-1rL3tXeg21oecEK3KM',
    appId: '1:878597889127:web:bbca637a788c0ccdd6c8c2',
    messagingSenderId: '878597889127',
    projectId: 'rideshare-app-8a30a',
    authDomain: 'rideshare-app-8a30a.firebaseapp.com',
    databaseURL: 'https://rideshare-app-8a30a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rideshare-app-8a30a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUc86jcYbFLhNJr55vNVDaDvf-ORaA60c',
    appId: '1:878597889127:android:4c7148ef9d356223d6c8c2',
    messagingSenderId: '878597889127',
    projectId: 'rideshare-app-8a30a',
    databaseURL: 'https://rideshare-app-8a30a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rideshare-app-8a30a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrQFZbVEWjmzu1Ghtm0Ygb8L0_Pz2Pelw',
    appId: '1:878597889127:ios:c25c1dfeff3e6e15d6c8c2',
    messagingSenderId: '878597889127',
    projectId: 'rideshare-app-8a30a',
    databaseURL: 'https://rideshare-app-8a30a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rideshare-app-8a30a.firebasestorage.app',
    iosBundleId: 'com.example.rideshareApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrQFZbVEWjmzu1Ghtm0Ygb8L0_Pz2Pelw',
    appId: '1:878597889127:ios:c25c1dfeff3e6e15d6c8c2',
    messagingSenderId: '878597889127',
    projectId: 'rideshare-app-8a30a',
    databaseURL: 'https://rideshare-app-8a30a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rideshare-app-8a30a.firebasestorage.app',
    iosBundleId: 'com.example.rideshareApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPOqtwt9qaajf_-1rL3tXeg21oecEK3KM',
    appId: '1:878597889127:web:900c7a3d03f835bad6c8c2',
    messagingSenderId: '878597889127',
    projectId: 'rideshare-app-8a30a',
    authDomain: 'rideshare-app-8a30a.firebaseapp.com',
    databaseURL: 'https://rideshare-app-8a30a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rideshare-app-8a30a.firebasestorage.app',
  );
}
